apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.auth.name }}

spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.auth.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.auth.name }}
    spec:
      {{- if .Values.auth.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.auth.imagePullSecrets.name }}
      {{- end }}
      containers:
      - name: {{ .Values.auth.name }}
        image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
        imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
        {{- if .Values.auth.startupCommand.enabled }}
        command: 
          - {{ .Values.auth.startupCommand.shell | quote }}
          - "-c"
        args:
          - |
{{ .Values.auth.startupCommand.command | indent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.auth.service.portOne }}
        - containerPort: {{ .Values.auth.service.portTwo }}

        {{- if .Values.auth.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.auth.grpcPort }}
          initialDelaySeconds: {{ .Values.auth.livenessProbe.initialDelaySeconds | default 15 }}
          periodSeconds: {{ .Values.auth.livenessProbe.periodSeconds | default 30 }}
          failureThreshold: {{ .Values.auth.livenessProbe.failureThreshold | default 3 }}
        {{- end }}
        
        {{- if .Values.auth.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.auth.grpcPort }}
          initialDelaySeconds: {{ .Values.auth.readinessProbe.initialDelaySeconds | default 15 }}
          periodSeconds: {{ .Values.auth.readinessProbe.periodSeconds | default 30 }}
          failureThreshold: {{ .Values.auth.readinessProbe.failureThreshold | default 3 }}
        {{- end }}

        {{- if .Values.auth.startupProbe.enabled }}
        startupProbe:
          tcpSocket:
            port: {{ .Values.auth.grpcPort }}
          initialDelaySeconds: {{ .Values.auth.startupProbe.initialDelaySeconds | default 15 }}
          periodSeconds: {{ .Values.auth.startupProbe.periodSeconds | default 30 }}
          failureThreshold: {{ .Values.auth.startupProbe.failureThreshold | default 3 }}
        {{- end }}


        {{- if .Values.auth.volumes.enabled }}
        volumeMounts:
        {{- if .Values.auth.volumes.env.enabled }}
        - name: env-volume
          mountPath: {{ .Values.auth.volumes.env.mountPath | quote }}
          subPath: {{ .Values.auth.volumes.env.subPath }}
        {{- end }}
        {{- if .Values.auth.volumes.logs.enabled }}
        - name: log-volume
          mountPath: {{ .Values.auth.volumes.logs.mountPath | quote }}
          subPath: {{ .Values.auth.volumes.logs.subPath }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.auth.resources | nindent 10 }}
      {{- if .Values.auth.affinity.enabled }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- range .Values.auth.affinity.preferredNodes }}
          - weight: {{ .weight }}
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .hostname }}
          {{- end }}
      {{- end }}
      {{- if .Values.auth.volumes.enabled }}
      volumes:
      {{- if .Values.auth.volumes.env.enabled }}
      - name: env-volume
        persistentVolumeClaim:
          claimName: {{ .Values.auth.volumes.env.pvcName }}
      {{- end }}
      {{- if .Values.auth.volumes.logs.enabled }}
      - name: log-volume
        persistentVolumeClaim:
          claimName: {{ .Values.auth.volumes.logs.pvcName }}
      {{- end }}
      {{- end }}