{{- if .Values.auth.auth.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.auth.name }}-auth
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.auth.name }}-deployment
  minReplicas: {{ .Values.auth.auth.minReplicas }}
  maxReplicas: {{ .Values.auth.auth.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.auth.auth.cpuUtilization }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        value: {{ .Values.auth.auth.scaleUp.podsValue }}
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: {{ .Values.auth.auth.scaleDown.podsValue }}
        periodSeconds: 60
{{- end }}