apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.frontend.name }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      {{- if .Values.frontend.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.frontend.imagePullSecrets.name }}
      {{- end }}
      containers:
      - name: {{ .Values.frontend.name }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        {{- if .Values.frontend.startupCommand.enabled }}
        command: 
          - {{ .Values.frontend.startupCommand.shell | quote }}
          - "-c"
        args:
          - |
{{ .Values.frontend.startupCommand.command | indent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}

        {{- if .Values.frontend.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.frontend.livenessProbe | nindent 10 }}
        {{- end }}
        
        {{- if .Values.frontend.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.frontend.readinessProbe | nindent 10 }}
        {{- end }}
        
        {{- if .Values.frontend.startupProbe }}
        startupProbe:
          {{- toYaml .Values.frontend.startupProbe | nindent 10 }}
        {{- end }}


        {{- if .Values.frontend.volumes.enabled }}
        volumeMounts:
        {{- if .Values.frontend.volumes.env.enabled }}
        - name: env-volume
          mountPath: {{ .Values.frontend.volumes.env.nginxOneMountPath | quote }}
          subPath: {{ .Values.frontend.volumes.env.nginxOneSubPath }}
        - name: env-volume
          mountPath: {{ .Values.frontend.volumes.env.nginxTwoMountPath | quote }}
          subPath: {{ .Values.frontend.volumes.env.nginxTwoSubPath }}
        {{- end }}

        {{- if .Values.frontend.volumes.logs.enabled }}
        - name: log-volume
          mountPath: {{ .Values.frontend.volumes.logs.mountPath | quote }}
          subPath: {{ .Values.frontend.volumes.logs.subPath }}
        {{- end }}
        {{- end }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
      {{- if .Values.frontend.affinity.enabled }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          {{- range .Values.frontend.affinity.preferredNodes }}
          - weight: {{ .weight }}
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .hostname }}
          {{- end }}
      {{- end }}
      {{- if .Values.frontend.volumes.enabled }}
      volumes:
      {{- if .Values.frontend.volumes.env.enabled }}
      - name: env-volume
        persistentVolumeClaim:
          claimName: {{ .Values.frontend.volumes.env.pvcName }}
      {{- end }}
      {{- if .Values.frontend.volumes.logs.enabled }}
      - name: log-volume
        persistentVolumeClaim:
          claimName: {{ .Values.frontend.volumes.logs.pvcName }}
      {{- end }}
      {{- end }}