---
- name: A. Copying script to remote system
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/remote-server-files/scripts/%script.sh%"
    dest: "/tmp/%script.sh%"
    mode: '0755'

- name: B. K8s setup via script
  ansible.builtin.shell: /tmp/%script.sh%
  args:
    executable: /bin/bash
  register: %script_output%

- name: C. Display output
  ansible.builtin.debug:
    var: %script_output%.stdout_lines

- name: D. Clean up script from remote system
  ansible.builtin.file:
    path: /tmp/%script.sh%
    state: absent