namespace:
  name: default


lavinmq:
  name: my-first-lavinmq
  namespace: default
  replicas: 2
  image: cloudamqp/lavinmq:latest
  accessMode: ReadWriteOnce
  amqpPort: 5672
  mgmtPort: 15672
  # clustering: true

storageClass: manual-storage


pv:
  enabled: true
  size: 5Gi
  accessMode: ReadWriteOnce
  nfsServer: nfs.agentcisinteral.com
  nfsPathOne: /agentcis-pvc/helm-test/lavinmq-data-0
  reclaimPolicy: Retain
  nameOne: lavinmq-pv-0
  nameTwo: lavinmq-pv-1



service:
  enabled: true
  name: my-test-lavinmq-nodeport
  type: NodePort
  protocol: TCP
  nameUi: http-ui
  portOne: 15672
  targetPortOne: 15672
  nodePortOne: 31672
  nameAmqp: amqp
  portTwo: 5672
  targetPortTwo: 5672
  nodePortTwo: 30672
