namespace:
  name: lavinmq-infra

# -----------------------------------------------
# LavinMQ instance config
# -----------------------------------------------
lavinmq:
  name: lavinmq
  replicas: 2
  image: cloudamqp/lavinmq:2.6.8
  accessMode: ReadWriteOnce
  amqpPort: 5672
  mgmtPort: 15672
  etcdEndpoint: "http://lavinmq-etcd.lavinmq-infra.svc.cluster.local:2379"



# -----------------------------------------------
# Storage config (used by my-lavinmq.yaml)
# -----------------------------------------------
pv:
  size: 5Gi
  storageClass: nfs-client-lavinmq         # ← must match storageClass.name above


# -----------------------------------------------
# NodePort service config
# -----------------------------------------------
service:
  enabled: true
  name: lavinmq-nodeport
  type: NodePort
  protocol: TCP
  nameUi: http-ui
  portOne: 15672
  targetPortOne: 15672
  nodePortOne: 31672
  nameAmqp: amqp
  portTwo: 5672
  targetPortTwo: 5672
  nodePortTwo: 30672