apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"    # ← deploys first
spec:
  project: default
  source:
    repoURL: "https://github.com/alija-globaly/argo.git"
    targetRevision: "main"
    path: "agentcis-app-gitops-staging/gitops/charts/self-managed/cert-manager"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      