apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lavinmq-etcd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: etcd
    targetRevision: "12.0.18"
    helm:
      valueFiles:
      - values/staging/root-app-values/lavinmq-etcd-values.yaml  # ← relative path
  - repoURL: https://github.com/alija-globaly/argo.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: lavinmq-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
