apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lavinmq-instance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"    # ← deploys last
spec:
  project: default
  source:
    repoURL: https://registry-1.docker.io/bitnamicharts
    targetRevision: "main"
    path: "agentcis-app-gitops-staging/gitops/charts/self-managed/lavinmq-instance"
  destination:
    server: https://kubernetes.default.svc
    namespace: lavinmq-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      