---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.backendConsumer.pv.config.name }}
spec:
  capacity:
    storage: {{ .Values.backendConsumer.pv.config.capacity | default "5Gi" }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.backendConsumer.pv.config.reclaimPolicy | default "Retain" }}
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: {{ .Values.backendConsumer.pv.config.nfsPath }}
    server: {{ .Values.backendConsumer.pv.config.nfsServer }}



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backendConsumer.volumes.env.pvcName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.backendConsumer.pv.config.capacity | default "5Gi" }}
  volumeName: {{ .Values.backendConsumer.pv.config.name }}
  storageClassName: ""