# NFS provisioner for etcd
nfs-lavinmq-etcd:
  nfs:
    server: nfs.agentcisinteral.com
    path: /agentcis-pvc/lavinmq-etcd-data
  storageClass:
    name: nfs-client-etcd
    reclaimPolicy: Retain
    archiveOnDelete: "false"

# NFS provisioner for lavinmq
nfs-lavinmq:
  nfs:
    server: nfs.agentcisinteral.com
    path: /agentcis-pvc/lavinmq-data
  storageClass:
    name: nfs-client-lavinmq
    reclaimPolicy: Retain
    archiveOnDelete: "false" 