namespace:
  name: cert-manager

cert-manager:
  installCRDs: true       # ← installs cert-manager CRDs automatically
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
