apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentcisapp-parent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background   
spec:
  project: microservice
  source:
    repoURL: "https://github.com/GlobalyHub/agentcis-app-gitops.git"
    targetRevision: "staging"          # branch to deploy
    path: "gitops/charts/self-managed/backend" # path to the Helm chart
    helm:
      valueFiles:
        - $values/gitops/values/staging/root-app-values/agentcisapp-parent-values.yml   # your backend values file
  destination:
    server: https://kubernetes.default.svc
    namespace: agentcisapp-parent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true       
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground      