apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentcisapp-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/alija-globaly/argo.git"
    targetRevision: "main"
    path: "agentcis-app-gitops-staging/gitops/charts/self-managed/auth"
    helm:
      valueFiles:
        - ../../../values/staging/root-app-values/auth-values.yml 
  destination:
    server: https://kubernetes.default.svc
    namespace: agentcisapp-auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground