apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentcis-data-import-backend-consumer-test
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io/background  

spec:
  project: default
  source:
    repoURL: "https://github.com/alija-globaly/argo.git"
    targetRevision: "main"          # branch to deploy
    path: "agentcis-app-gitops-staging/gitops/charts/self-managed/backend-consumer" # path to the Helm chart
    helm:
      valueFiles:
        - ../../../values/staging/root-app-values/data-import-api-consumer-values.yml   # your backend consumer values file
  destination:
    server: https://kubernetes.default.svc
    namespace: agentcis-data-import-backend-consumer-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true       
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground 
