# templates/my-lavinmq.yaml
apiVersion: cloudamqp.com/v1alpha1
kind: LavinMQ
metadata:
  name: {{ .Values.lavinmq.name }}
  namespace: {{ .Values.lavinmq.namespace }}

spec:
  replicas: {{ .Values.lavinmq.replicas }}
  image: {{ .Values.lavinmq.image }}


  etcdEndpoints: 
      - "http://my-etcd.default.svc.cluster.local:2379"

  dataVolumeClaim:
    accessModes:
      - {{ .Values.lavinmq.accessMode }}
    resources:
      requests:
        storage: {{ .Values.pv.size }}
    storageClassName: {{ .Values.storageClass }}
  config:
    amqp:
      port: {{ .Values.lavinmq.amqpPort }}
    mgmt:
      port: {{ .Values.lavinmq.mgmtPort }}
 