apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: "{{ .Values.pv.size }}"
  accessModes:
    - {{ .Values.pv.accessMode }}
  nfs:
    server: {{ .Values.pv.nfsServer }}
    path: {{ .Values.pv.nfsPath }}
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  storageClassName: {{ .Values.pv.storageClass | quote }}
